<a href="https://colab.research.google.com/github/morganpatito/Computational-Physics/blob/main/Python_Tutorials/Chapter_8_NumPy_arrays_2D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Chapter 8 - Multidimensional NumPy Arrays

Goals
* Create, use and modify multidimensional NumPy arrays (2D, 3D, etc.)
* Apply functions to multidimensional arrays
* Read in a comma-separated-value (csv) data file






## **8.0 Multidimensional Arrays**

This chapter describes how to create, apply and extract data from multi-dimensional arrays in 2D, 3D and higher dimensions.


## **8.1 Creating multidimensional arrays**






### **8.1.1 Creating 2D arrays**

* 2D Arrays are specified by an `(n,m)` tuple
* The first parameter `n` specifies the number rows
* The second parameter `m` specifies the number of columns.





### 🔆 Example:  Creating 2D array filled with zeros

* To fill a $2\times 3$ array (2 rows and 3 columns) with zeros, we can use the `np.zeros((n,m))` command.
* The "double parentheses" are necessary, since the inner parentheses create a "tuple" which the `np.zeros()` function expects.

In [1]:
import numpy as np

A = np.zeros((2,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]]


### 🔆 Example: Creating an array of random integers

In the following example, we fill a 2x5 array with random integers between 1 and 9 inclusive.
* We specify the size of the array to have 3 rows and 5 columns using the `size=(3,5)` parameter.
* We use the `endpoint=True` parameter to tell Python to includ the upper limit (9 in this example).

In [4]:
rng = np.random.default_rng()        # create random number Generator

A = rng.integers(1, 9, size=(3,5),endpoint=True)
print(A)

[[2 6 1 2 3]
 [5 4 5 9 3]
 [9 1 3 2 8]]


### ✅ Skill Check 1

Create a 2D array with 6 columns and 3 rows. Each element should be a random  integer whose value satisfies $1 \leq x \leq 4$. Print the array.

In [5]:
# Your code here
import numpy as np

rng = np.random.default_rng()
A = rng.integers(1, 5, size=(3,6), endpoint=False)  # 1 ≤ x ≤ 4
print(A)


[[3 3 3 3 4 4]
 [3 1 2 4 3 1]
 [3 2 4 1 4 1]]


### **8.1.2 Creating 3D arrays**

* 3D arrays (i.e. tensors) are specified by a `(p,n,m)` tuple
* `p` = first parameter = the number of layers p of the array.
* `n` = 2nd parameter = the number rows n
* `m` = 3rd parameter = the number of columns m

* For example, to fill an  4x2×3  array (2 rows, 3 columns and 4 layers deep) with zeros, we can use the following:

In [6]:
A = np.zeros((4,2,3))
print(A)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


## **8.2 .shape, .size and .ndim attributes**

NumPy provides three attributes that characterize the shape and size of NumPy arrays. Remember that attributes do no use parentheses, while methods do.
* `.shape' returns a tuple containing the dimensions along each axis of the array.
* The number of elements along a given axis) can be extracted as follows:
* The first element is the number of rows:  `.shape[0]`
* The second element is the number of columns:  `.shape[1]`
* Higher-dimensional arrays (3D, 4D, etc.) will have information about the number of layers in the `[2]`, `[3]`,  etc. positions.


In [7]:

A = rng.integers(1, 9, size=(3,5),endpoint=True)
print("A = ")
print(A)

print()
print("shape of A is ",A.shape)

n_rows = A.shape[0]              # extract the number of rows
n_cols = A.shape[1]              # extract the number of columns

print("number of rows in A    =",n_rows)
print("number of columns in A =",n_cols)

A = 
[[2 3 4 3 3]
 [2 5 3 2 4]
 [8 9 4 3 9]]

shape of A is  (3, 5)
number of rows in A    = 3
number of columns in A = 5


* `.size` returns the total number of elements in A, which equals the (number of rows) $\times$ (number of columns) for a 2D array
* `.ndim` returns the number of dimensions, which is 2 for a 2D array, 3 for a 3D array, etc.

In [8]:
print("size of A (total # elements) =",A.size)
print("number of dimensions of A    =",A.ndim)

size of A (total # elements) = 15
number of dimensions of A    = 2


### 🔆 Example:  4D Array

Here's an example of creating a 4D array:
* number of columns = 5
* number of rows = 4
* number of layers = 3
* number of blocks of layers = 2

In [9]:
z = np.zeros((2,3,4,5))

print("shape of z (length along each axis) =",z.shape)
print("size of z (total # elements) =",z.size)
print("number of dimensions of A    =",z.ndim)
print()
print("z = ")
print(z)

shape of z (length along each axis) = (2, 3, 4, 5)
size of z (total # elements) = 120
number of dimensions of A    = 4

z = 
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


### **8.4 Accessing elements in multi-dimensional arrays**

The following examples show how to access and slice a 2D array.


In [10]:
rng = np.random.default_rng()    # create random number Generator
A = rng.integers(1, 9, size=(3,5),endpoint=True)

print("A = ")
print(A)                         # prints array A
print()                          # prints a blank line

print("A[0,2]  =  ",A[0,2])      # top row, 3rd column
print("A[0,:2] =  ",A[0,1:3])    # top row, columns 2 and 3
print("A[0,:]  =  ",A[0,:])      # top row
print("A[0,:]  =  ",A[:,1])      # second column
print()
print("A[0:2,0:2] = ")           # 2x2 matrix from top-left corner of A
print(A[0:2,0:2])

A = 
[[6 5 8 5 7]
 [2 3 9 7 3]
 [9 6 9 1 1]]

A[0,2]  =   8
A[0,:2] =   [5 8]
A[0,:]  =   [6 5 8 5 7]
A[0,:]  =   [5 3 6]

A[0:2,0:2] = 
[[6 5]
 [2 3]]


The following over-writes the top row of our 2D array with zeros.
* Note:  we use the `.shape` attribute to automatically determine how many columns are in `A`, which we pass to the `np.zeros()` function.

In [11]:
A[0,:] = np.zeros(A.shape[1])
print(A)

[[0 0 0 0 0]
 [2 3 9 7 3]
 [9 6 9 1 1]]


### ✅ Skill Check 2

* Use slicing to set the last column of the `A` array defined above to 1's
* print the `A` array



In [12]:
# your code here
A[:,-1] = 1   # last column (index -1)
print(A)


[[0 0 0 0 1]
 [2 3 9 7 1]
 [9 6 9 1 1]]


## **8.5 Working with multi-dimensional arrays**



### 8.5.1 Create a new array to match size of an existing array

* We can use the `.shape` attribute to easily create a new array with the same size as an existing array like this:


In [13]:
A = rng.integers(1, 9, size=(3,5),endpoint=True)

B = np.zeros(A.shape)     # Array B will have same size as array A
print(B)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### 8.5.2 Take the transpose of a 2D array

* The transpose flips the rows and columns
* We just add a `.T` after our array like this:  `A.T`
* We'll take the transpose of the `A` array in the previous section:

In [14]:
print("original Array, A:")
print(A)
print()

print("transpose of A:")
print(A.T)

original Array, A:
[[9 2 2 7 3]
 [6 6 1 5 6]
 [6 8 3 1 1]]

transpose of A:
[[9 6 6]
 [2 6 8]
 [2 1 3]
 [7 5 1]
 [3 6 1]]


### 8.5.3  Reshaping arrays

**Flatten**

* We can reduce an array to 1D with the `.flatten()` method.
* Notice that

In [15]:
print("flattened version of A")
A_flat = A.flatten()
print(A_flat)


flattened version of A
[9 2 2 7 3 6 6 1 5 6 6 8 3 1 1]


**Reshape**

* The `.reshape()` method can be used to reorder the elements of an array.
* The  `.reshape()` method takes a tuple as an argument:  single number for 1D array, `(n,m)` for 2D array, `(p,n,m)` for a 3D array and so on.

In [16]:
#####  Create a 1x12 array filled with integers
print("original array. A ")
A = np.linspace(1,12,12,dtype=int)
print(A)

#####  Reshape -> 2x6  (2 rows, 6 columns)
print()
print("A2 = A.reshape((2,6)) ")
A2 = A.reshape((2,6))
print(A2)
print()

#####  Reshape -> 3x4  (3 rows, 4 columns)
print("A3 = A2.reshape((3,4)) ")
A3 = A2.reshape((3,4))
print(A3)
print()

#####  Reshape -> 2x2x3  (2 layers, 2 rows, 3 columns) = 3D array
print("A4 = A3.reshape((2,2,3)) ")
A4 = A3.reshape((2,2,3))
print(A4)


original array. A 
[ 1  2  3  4  5  6  7  8  9 10 11 12]

A2 = A.reshape((2,6)) 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

A3 = A2.reshape((3,4)) 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

A4 = A3.reshape((2,2,3)) 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### 8.5.4 Analyzing Arrays along Rows or Columns

* Suppose you are given a 2D array, and you'd like to know something about the first column.

### 8.5.4 Computing statistics along rows or columns

* Suppose you are given a 2D array, and you'd like to know something about the first column.
* We can use slicing to extract the column for analysis
* We can also specify the dimension we want to analyz

In [17]:
R = np.linspace(1,15,15)
R = R.reshape((5,3))
R = R.T
print("R = ")
print(R)

ave = R.mean(axis = 0)
print()
print("Column mean = ")
print(ave)

ave = R.mean(axis = 1)
print()
print("Row mean = ")
print(ave)

R = 
[[ 1.  4.  7. 10. 13.]
 [ 2.  5.  8. 11. 14.]
 [ 3.  6.  9. 12. 15.]]

Column mean = 
[ 2.  5.  8. 11. 14.]

Row mean = 
[7. 8. 9.]


## 8.6 Reading data files in Google Colab

Google Colab poses some challenges when reading and writing files due to the way Google handles directories. When we run Python on your laptop, this process will be much simpler.
* Step 1 - Download the file `bh_merger.csv` from the Python_Tutorials directory on GitHub and save it on your laptop. This file contains the masses of binary black hole pairs that have merged and given off gravitational waves.
* Step 2 - Run the following Code Cell. This will load in the data in from the file and save it as a 2D NumPy array called `data`.
* Step 3 - Once the data is successfully read in to the `data` array, the data will be saved in memory, so you can run or rerun the analysis code in the following Code Cells without having to reload the file.

Here's what the following Code Cell does to read in the data file:
* Import the `google.files` module
* Call `uploaded = files.upload()` to launch a file picker. You'll need to navigate to you the `bh_merger.csv` file to load it.
* Extract the actual file name from the `uploaded` dictionary using the command `file_name = list(uploaded.keys())[0]`
* Finally, we can now use the NumPy command `np.loadtxt(file_name)` to load a file specified by `file_name`.

Use of the `np.loadtxt()` command
* `np.loadtxt(file_name)` loads a data file with name `file_name`. The file must contain rows of numeric values with equal number of values per row, with each numerica value separated by spaces. The file cannot have any extra header or footer data. Thus, the file must have the form:  
```
   1.0  2.4  3.6
   3.5  0.1  0.4
   4.3  2.1  3.5
```
* If the values are separated by commas as in the following example, we need to specify the delimeter between values is a comma like this:  `np.loadtxt(file_name,delimiter=',')`.  
```
   1.0, 2.4, 3.6
   3.5, 0.1, 0.4
   4.3, 2.1, 3.5
```
* If the file has one or more header lines, we need to skip over them to read the data. We specify the number of lines to skip with the `skiprows` parameter like this:   `np.loadtxt(file_name, skiprows=1,delimiter=',')`.  
```
   x, y, z
   1.0, 2.4, 3.6
   3.5, 0.1, 0.4
   4.3, 2.1, 3.5
```
* Our `bh_merger.csv` file has one header line and uses a comma delimiter, so we use the command `data = np.loadtxt(file_name,skiprows=1,delimiter=',')` to read it.

In [18]:
# Import Libraries
from google.colab import files   # used to load files in Google
import numpy as np

#####  Load Data File
uploaded = files.upload()  # This opens a file picker

# uploaded is a dictionary: filename -> bytes
# Get the first filename
file_name = list(uploaded.keys())[0]

# Load the data into a NumPy array
# Assuming a text file with numeric data, separated by commas
#    and with one header line that must be skipped
data = np.loadtxt(file_name,skiprows=1,delimiter=',')



Saving bh_merger.csv to bh_merger.csv


The `bh_merger.csv` file contains the following columns of data:
* column 1 - mass of first black hole in units of solar masses (i.e. 30 means the black hole has 30 times the mass of the sun).
* column 2 - mass of the second black hole
* column 3 - distance of the black holes from Earth in units of megaparsecs (Mpc). 1 Mpc = 3.26 million light years.

The following Code prints the number of rows, columns and first 5 rows of data.


In [20]:
# Inspect the array
nrows = data.shape[0]
ncols = data.shape[1]
print()
print(f"{file_name} contains {nrows} rows and {ncols} columns")
print()
print("First 5 rows:")
print(data[:5])


bh_merger.csv contains 174 rows and 3 columns

First 5 rows:
[[  29.1   18.  1450. ]
 [  60.    32.  5700. ]
 [  42.3   32.3 1890. ]
 [  22.5   17.2 1060. ]
 [  53.    35.  5600. ]]


### ✅ Skill Check 3

The following code shows how to extract the first column of values from the `data` array and name it mass1 (this will contain the masses of one of black holes in the binary system.)
* Extract the second column and name it `mass2` (mass of second black hole)
* Exctract the third column and name it `dist` (distance of the black holes)

In [36]:
mass1 = data[:,0]  # mass one is stored in the first column (index = 0)
mass2 = data[:,1]   # second column
dist  = data[:,2]   # third column




### ✅ Skill Check 4

* Calculate and print the minimum, maximum and average mass for for `mass1`. Use the NumPy vectorized methods
* Calculate and print the minimum, maximum and average mass for for `mass2`. Use the NumPy vectorized methods
* Calculate and print the minimum, maximum and average distance of the black holes. Use the NumPy vectorized methods.
* Convert the distance of the most distant black hole into billions of light years (multiply the distance in Mpc by 3262). For nearby objects, this would be how far back in the past light left the object that we are now seeing. However, these distant black holes are so far away, we would need to take into account the acceleration of the universe after the Big Bang, which only happened about 13.8 billion years ago.

In [37]:
# your code here
print("Mass 1 stats:")
print("min =", mass1.min(), " max =", mass1.max(), " mean =", mass1.mean())

print("Mass 2 stats:")
print("min =", mass2.min(), " max =", mass2.max(), " mean =", mass2.mean())

print("Distance stats (Mpc):")
print("min =", dist.min(), " max =", dist.max(), " mean =", dist.mean())

# Convert max distance to billions of light years
farthest_bly = dist.max() * 3262 / 1e9
print("Most distant black hole system is about", farthest_bly, "billion light years away")


Mass 1 stats:
min = 1.46  max = 137.0  mean = 37.57448275862068
Mass 2 stats:
min = 1.17  max = 103.0  mean = 23.67706896551724
Distance stats (Mpc):
min = 40.0  max = 8280.0  mean = 2502.787356321839
Most distant black hole system is about 0.02700936 billion light years away


### ✅ Skill Check 5

* Reshape the the first two columns of the the `data` array to create a single array containing the masses of both black holes.
* Calculate the minimum, maximum and average of all the black holes.
* Are your values consistent with your stats for `mass1` and `mass2`?

In [38]:
# your code here
# Reshape to put both columns into one array
masses = data[:,0:2].reshape(-1)   # flatten both columns into 1D
print("All masses =", masses)

print("Stats of all black holes:")
print("min =", masses.min(), " max =", masses.max(), " mean =", masses.mean())


All masses = [ 29.1   18.    60.    32.    42.3   32.3   22.5   17.2   53.    35.
  40.    35.3    9.3    7.32  11.1    8.3   12.     6.8   46.    31.
  48.    29.    35.3   27.4   37.6   28.5   35.9   28.6   46.    23.6
  46.    29.   137.   103.    48.    34.    13.2    7.2   43.    30.
  20.2   10.8   23.1    8.2   11.6    7.4   40.2   27.4   19.6   12.6
  23.2   17.4   12.3    8.6   62.    43.    65.    42.    99.    55.
  12.2    7.3   11.6    7.3   20.6   14.8   46.    25.1   28.5   21.6
  85.    49.    66.    34.    77.    40.    34.1   24.6   55.    30.
  21.9   16.6   34.9   27.4   28.7   23.2   76.    51.    39.8   29.3
  32.5   24.2   27.5   21.7   60.    36.    36.2   20.3   10.6    7.1
  43.    31.    45.    27.8   53.    36.    64.    32.    73.    33.
  33.6   28.4   72.    43.    36.4   21.7   51.    35.    32.3   22.7
  46.    29.    10.3    7.8   12.4    7.6   35.3   28.    16.7   10.8
  32.    11.4   45.    30.    65.    39.    29.1   23.1   45.9   36.8
  16.3   11.5

## Key Points
* NumPy arrays can be 1D, 2D, 3D, 4D, or any number of dimensions
* Fetching values from a multidimensional array uses commas, i.e `A[1,0,3]`
* NumPy arrays have many Attributes an Methods to perform operations and gather statistics.
* Loading data into Google Colab is more complicated than doing so on your laptop. We showed how to load a comma-separated-value (csv) file and analyze the data

This tutorial is an adaptation of "[Python for Physicists](https://lucydot.github.io/python_novice/)"
© [Software Carpentry](http://software-carpentry.org/)
